### ISSUE TITLE
cchardet-1.0.0-cp34-none-win_amd64.whl build is missing.

### ISSUE THREAD

**Issue by luckcolors** [PyYoshi/cChardet#14]
Hello.
I need the cchardet build for windows 64 but it's missing could you please compile the missing one?
https://pypi.python.org/pypi/cchardet/1.0.0
Thanks in advance. :)

**Comment by PyYoshi** [comment]
Hi luckcolors!

Sorry for my late reply :cry: 

I just supported 3.4/3.5 windows 64bit binaries. check this [here](https://pypi.python.org/pypi/cchardet/1.1.0)  :smile:

**Comment by luckcolors** [comment]
Thanks man!
Yeah also sorry for this late reply. :)
