### ISSUE TITLE
Installation on OSX fails

### ISSUE THREAD

**Issue by themightyoarfish** [PyYoshi/cChardet#15]
```
$ sudo pip install cchardet
$ python -c "import cchardet"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/cchardet/__init__.py", line 4, in <module>
    from cchardet import _cchardet
ImportError: dlopen(/Library/Python/2.7/site-packages/cchardet/_cchardet.so, 2): no suitable image found.  Did find:
    /Library/Python/2.7/site-packages/cchardet/_cchardet.so: mach-o, but wrong architecture
```

When running the install manually without pip, it works.

System Info: OSX 10.10.5

**Comment by PyYoshi** [comment]
Hi @themightyoarfish!

How did you install python on OSX? (I'm using only [pyenv](https://github.com/yyuu/pyenv). XD

I'd like to hear more details.

**Comment by themightyoarfish** [comment]
`python` is resolve to the macports Python 2.7 install. I think pip also uses that.

**Comment by PyYoshi** [comment]
Can you install cython before you install cchardet?

```bash
$ sudo pip install cython
$ sudo pip install cchardet
```

**Comment by themightyoarfish** [comment]
I have install cython, or do you think it is significant that I do it with
pip? Since it is not in `/opt/local/bin` but in `/usr/local/bin`, I reckon
it was installed with pip or came preinstalled.


On 22 May 2016 at 13:32:40, Yoshihiro Misawa (notifications@github.com)
wrote:

Can you install cython before you install cchardet?

$ sudo pip install cython
$ sudo pip install cchardet

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/PyYoshi/cChardet/issues/15#issuecomment-220827608>
