### ISSUE TITLE
confidence=0 when scanning ASCII text

### ISSUE THREAD

**Issue by craigds** [PyYoshi/cChardet#17]
`cchardet` gives confidence of 0.0 when scanning ascii text. This is inconsistent with `chardet`'s behaviour:

``` python
>>> import chardet
>>> import cchardet
>>> import string
>>> chardet.detect(string.ascii_letters*1000)
{'confidence': 1.0, 'encoding': 'ascii'}
>>> cchardet.detect(string.ascii_letters*1000)
{'confidence': 0.0, 'encoding': u'ASCII'}
```

The size of the document makes no difference; the returned confidence is always 0.0.

1.0 would seem to be more correct since the document has no non-ASCII characters.

**Comment by christian-storm** [comment]
I'm having the same issue for what it is worth.

**Comment by PyYoshi** [comment]
Hi @craigds and @christian-storm 

Sorry for my late reply.

I fixed [v2 branch](https://github.com/PyYoshi/cChardet/tree/v2).

Please check it out.
