### ISSUE TITLE
Is this an detect error

### ISSUE THREAD

**Issue by rhinoceros** [PyYoshi/cChardet#19]
python 2.7.11
cchardet-1.1.1-cp27-cp27m-win_amd64.whl (md5)
window server 2008 r2 enterprise
system language: chinese simple (操作系统显示语言：简体中文）
test.py is the python code
testfile.cs is the input file (open by notepad, [save as（另存） ] show the encode（编码） is ANSI
testfile.chardet.cs  is the output file: decode by chardet.detect(raw)['encoding'] ,then , encode by utf8
testfile.cchardet.cs is the output file: decode by cchardet.detect(raw)['encoding'] ,then , encode by utf8
testfile.GB2312.cs   is the output file: decode by 'GB2312' ,then , encode by utf8.

testfile.GB2312.cs  is the RIGHT.

[test_chardet.zip](https://github.com/PyYoshi/cChardet/files/579797/test_chardet.zip)

**Comment by PyYoshi** [comment]
Hi rhinoceros.

Maybe. It's not enough sample data for cchardet.

I modified ``test.py``.

```diff
--- test.py.old	2016-11-09 16:01:05.983586070 +0900
+++ test.py	2016-11-09 16:04:09.115603061 +0900
@@ -25,9 +25,10 @@
         print '[WARN] filepath is not a file: ' + file_path
 
     # Read from file
-    file_open = open(file_path)
+    file_open = open(file_path, 'rb')
     raw = file_open.read()
     file_open.close()
+    raw = raw + raw
 
     file_encoding_chardet = str(chardet.detect(raw)['encoding'])
     file_encoding_cchardet = str(cchardet.detect(raw)['encoding'])
```

and do this.

```bash
$ python test.py

[INFO]  chardet code is : GB2312
[INFO] cchardet code is : GB18030
```

Thanks.

**Comment by rhinoceros** [comment]
I see , thks.
