### ISSUE TITLE
Segmentation fault when fed `\x8f`

### ISSUE THREAD

**Issue by craigds** [PyYoshi/cChardet#20]
This code:
```python
from __future__ import unicode_literals
import cchardet
msg = b'\x8f'
d = cchardet.Detector()
d.feed(msg)
d.close()
print(d.result)
```

results in a segmentation fault (during `d.result`)

(Python 2.7.6, 2.7.12, 3.4.3)

**Comment by PyYoshi** [comment]
Hi craigds. Thank you for reporting.

@moden-py. Can you check this issue? Because I think that you are familiar with this.

**Comment by PyYoshi** [comment]
Hi @craigds 

Sorry for my late reply.

I fixed [v2 branch](https://github.com/PyYoshi/cChardet/tree/v2).

Please check it out.
