### ISSUE TITLE
misdetecting windows-1251 for mac-cyrillic

### ISSUE THREAD

**Issue by burner1024** [PyYoshi/cChardet#24]
Dialog.tra is in fact windows-1251.
```
import cchardet as chardet
f=sys.argv[1]
with open(f, "rb") as f:
  mess = f.read()
  result = chardet.detect(mess)
  print result
```
```
/1.py dialog.tra
{'confidence': 0.8082455396652222, 'encoding': u'MAC-CYRILLIC'}
```
[dialog.tra.zip](https://github.com/PyYoshi/cChardet/files/870684/dialog.tra.zip)

**Comment by PyYoshi** [comment]
Hi @burner1024 

Sorry for my late reply.

I fixed [v2 branch](https://github.com/PyYoshi/cChardet/tree/v2).

Please check it out.
