### ISSUE TITLE
cchardet-2.1.0.tar.gz dosen't contain COPYING file

### ISSUE THREAD

**Issue by futatuki** [PyYoshi/cChardet#32]
### OS/Arch
any

### Python version

any

### cChardet version
2.1.0

### What is the problem?
cchardet-2.1.0.tar.gz download from https://pypi.python.org/ don't contain COPYING file.

#### Expected behavior
COPYING file is contained in archive, (README.rst suggests to see COPYING file for License)

#### Actual behavior
It is not contain.

#### Steps to reproduce the behavior
fetch tarball from https://pypi.python.org/packages/source/c/cchardet/cchardet-2.1.0.tar.gz and then execute
  `gzip -d -c cchardet-2.1.0.tar.gz | tar tvf -`
etc.

**Comment by PyYoshi** [comment]
Thank you for reporting!

I released [v2.1.1](https://pypi.python.org/pypi/cchardet/2.1.1)

P.S: 必ずテンプレートに従うかたちではなくても構わないです. この場合はバグというわけではないので.
