### ISSUE TITLE
Failed to build cchardet - osx 10.13.3 with brew python3

### ISSUE THREAD

**Issue by rhamnett** [PyYoshi/cChardet#37]
Failed building wheel for cchardet
  Running setup.py clean for cchardet
Failed to build cchardet
Installing collected packages: cchardet, ccxt
  Running setup.py install for cchardet ... error
    Complete output from command /usr/local/opt/python/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/c6/t3s_sm6906j2lm2rcp2bdmqh0000gp/T/pip-build-ni2b6d85/cchardet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/c6/t3s_sm6906j2lm2rcp2bdmqh0000gp/T/pip-470mvm70-record/install-record.txt --single-version-externally-managed --compile:
    cythonize: ['src/cchardet/_cchardet.pyx']
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.13-x86_64-3.6
    creating build/lib.macosx-10.13-x86_64-3.6/cchardet
    copying src/cchardet/version.py -> build/lib.macosx-10.13-x86_64-3.6/cchardet
    copying src/cchardet/__init__.py -> build/lib.macosx-10.13-x86_64-3.6/cchardet
    running build_ext
    building 'cchardet._cchardet' extension
    creating build/temp.macosx-10.13-x86_64-3.6
    creating build/temp.macosx-10.13-x86_64-3.6/src
    creating build/temp.macosx-10.13-x86_64-3.6/src/cchardet
    creating build/temp.macosx-10.13-x86_64-3.6/src/ext
    creating build/temp.macosx-10.13-x86_64-3.6/src/ext/uchardet
    creating build/temp.macosx-10.13-x86_64-3.6/src/ext/uchardet/src
    creating build/temp.macosx-10.13-x86_64-3.6/src/ext/uchardet/src/LangModels
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Isrc/ext/uchardet/src -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c src/cchardet/_cchardet.cpp -o build/temp.macosx-10.13-x86_64-3.6/src/cchardet/_cchardet.o
    src/cchardet/_cchardet.cpp:1093:15: error: use of undeclared identifier 'assert'
      __pyx_t_1 = PyBytes_GET_SIZE(__pyx_v_msg); if (unlikely(__pyx_t_1 == ((Py_ssize_t)-1))) __PYX_ERR(1, 15, __pyx_L1_error)
                  ^
    /usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/include/python3.6m/bytesobject.h:89:32: note: expanded from macro 'PyBytes_GET_SIZE'
    #define PyBytes_GET_SIZE(op)  (assert(PyBytes_Check(op)),Py_SIZE(op))
                                   ^
    src/cchardet/_cchardet.cpp:1116:15: error: use of undeclared identifier 'assert'
      __pyx_t_2 = __Pyx_PyBytes_AsWritableString(__pyx_v_msg); if (unlikely((__pyx_t_2 == ((const char*)NULL)) && PyErr_Occurred())) __PYX_ERR(1, 19, __pyx_L1_error)
                  ^
    src/cchardet/_cchardet.cpp:596:56: note: expanded from macro '__Pyx_PyBytes_AsWritableString'
    #define __Pyx_PyBytes_AsWritableString(s)     ((char*) PyBytes_AS_STRING(s))
                                                           ^
    /usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/include/python3.6m/bytesobject.h:87:32: note: expanded from macro 'PyBytes_AS_STRING'
    #define PyBytes_AS_STRING(op) (assert(PyBytes_Check(op)), \
                                   ^
    src/cchardet/_cchardet.cpp:1206:57: error: use of undeclared identifier 'assert'
      __pyx_t_3 = (__pyx_v_detected_charset != Py_None) && (PyBytes_GET_SIZE(__pyx_v_detected_charset) != 0);
                                                            ^
    /usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/include/python3.6m/bytesobject.h:89:32: note: expanded from macro 'PyBytes_GET_SIZE'
    #define PyBytes_GET_SIZE(op)  (assert(PyBytes_Check(op)),Py_SIZE(op))
                                   ^
    src/cchardet/_cchardet.cpp:1553:15: error: use of undeclared identifier 'assert'
      __pyx_t_2 = PyBytes_GET_SIZE(__pyx_v_msg); if (unlikely(__pyx_t_2 == ((Py_ssize_t)-1))) __PYX_ERR(1, 64, __pyx_L1_error)
                  ^
    /usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/include/python3.6m/bytesobject.h:89:32: note: expanded from macro 'PyBytes_GET_SIZE'
    #define PyBytes_GET_SIZE(op)  (assert(PyBytes_Check(op)),Py_SIZE(op))
                                   ^
    src/cchardet/_cchardet.cpp:1577:17: error: use of undeclared identifier 'assert'
        __pyx_t_3 = __Pyx_PyBytes_AsWritableString(__pyx_v_msg); if (unlikely((__pyx_t_3 == ((const char*)NULL)) && PyErr_Occurred())) __PYX_ERR(1, 66, __pyx_L1_error)
                    ^
    src/cchardet/_cchardet.cpp:596:56: note: expanded from macro '__Pyx_PyBytes_AsWritableString'
    #define __Pyx_PyBytes_AsWritableString(s)     ((char*) PyBytes_AS_STRING(s))
                                                           ^
    /usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/include/python3.6m/bytesobject.h:87:32: note: expanded from macro 'PyBytes_AS_STRING'
    #define PyBytes_AS_STRING(op) (assert(PyBytes_Check(op)), \
                                   ^
    src/cchardet/_cchardet.cpp:1940:15: error: use of undeclared identifier 'assert'
      __pyx_t_2 = PyBytes_GET_SIZE(__pyx_t_1); if (unlikely(__pyx_t_2 == ((Py_ssize_t)-1))) __PYX_ERR(1, 93, __pyx_L1_error)
                  ^
    /usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/include/python3.6m/bytesobject.h:89:32: note: expanded from macro 'PyBytes_GET_SIZE'
    #define PyBytes_GET_SIZE(op)  (assert(PyBytes_Check(op)),Py_SIZE(op))
                                   ^
    src/cchardet/_cchardet.cpp:3817:19: error: use of undeclared identifier 'assert'
            *length = PyByteArray_GET_SIZE(o);
                      ^
    /usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/include/python3.6m/bytearrayobject.h:54:37: note: expanded from macro 'PyByteArray_GET_SIZE'
    #define PyByteArray_GET_SIZE(self) (assert(PyByteArray_Check(self)), Py_SIZE(self))
                                        ^
    src/cchardet/_cchardet.cpp:3818:16: error: use of undeclared identifier 'assert'
            return PyByteArray_AS_STRING(o);
                   ^
    /usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/include/python3.6m/bytearrayobject.h:52:6: note: expanded from macro 'PyByteArray_AS_STRING'
        (assert(PyByteArray_Check(self)), \
         ^
    8 errors generated.
    error: command 'clang' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/opt/python/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/c6/t3s_sm6906j2lm2rcp2bdmqh0000gp/T/pip-build-ni2b6d85/cchardet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/c6/t3s_sm6906j2lm2rcp2bdmqh0000gp/T/pip-470mvm70-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/c6/t3s_sm6906j2lm2rcp2bdmqh0000gp/T/pip-build-ni2b6d85/cchardet/

**Comment by rhamnett** [comment]
Had another incorrect assert.h on the path, in /usr/local/include

**Comment by nikolay** [comment]
It fails on macOS 10.14 as well. I did install the uchardet package, but it still doesn't change anything. Strangely, when I do `pip3 install --user --upgrade cchardet`, it works fine, but when it's getting updated as a dependency, it fails.

**Comment by pachecobruno** [comment]
Happens when I try to install version 1.3.3. Any idea?

```
pip install cchardet==1.1.3
Collecting cchardet==1.1.3
  Using cached https://files.pythonhosted.org/packages/da/f7/486e8e1c2e045d67dcbd05e4cf3a2ae16632001172ec61f757c6c56fa2da/cchardet-1.1.3.tar.gz
Installing collected packages: cchardet
  Running setup.py install for cchardet ... error
    Complete output from command /Users/brunopacheco/workspace/superset/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/_q/6ldlfbyd4hl0qrh0dd9kz2y00000gn/T/pip-install-ba1vcoc8/cchardet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/_q/6ldlfbyd4hl0qrh0dd9kz2y00000gn/T/pip-record-pjh8nvf6/install-record.txt --single-version-externally-managed --compile --install-headers /Users/brunopacheco/workspace/superset/venv/include/site/python3.7/cchardet:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.7
    creating build/lib.macosx-10.9-x86_64-3.7/cchardet
    copying src/cchardet/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/cchardet
    copying src/cchardet/version.py -> build/lib.macosx-10.9-x86_64-3.7/cchardet
    running build_ext
    building 'cchardet._cchardet' extension
    creating build/temp.macosx-10.9-x86_64-3.7
    creating build/temp.macosx-10.9-x86_64-3.7/src
    creating build/temp.macosx-10.9-x86_64-3.7/src/cchardet
    creating build/temp.macosx-10.9-x86_64-3.7/src/ext
    creating build/temp.macosx-10.9-x86_64-3.7/src/ext/libcharsetdetect
    creating build/temp.macosx-10.9-x86_64-3.7/src/ext/libcharsetdetect/mozilla
    creating build/temp.macosx-10.9-x86_64-3.7/src/ext/libcharsetdetect/mozilla/extensions
    creating build/temp.macosx-10.9-x86_64-3.7/src/ext/libcharsetdetect/mozilla/extensions/universalchardet
    creating build/temp.macosx-10.9-x86_64-3.7/src/ext/libcharsetdetect/mozilla/extensions/universalchardet/src
    creating build/temp.macosx-10.9-x86_64-3.7/src/ext/libcharsetdetect/mozilla/extensions/universalchardet/src/base
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -Isrc/ext/libcharsetdetect/mozilla/extensions/universalchardet/src/base/ -Isrc/ext/libcharsetdetect/nspr-emu/ -Isrc/ext/libcharsetdetect/ -I/Users/brunopacheco/workspace/superset/venv/include -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/cchardet/_cchardet.cpp -o build/temp.macosx-10.9-x86_64-3.7/src/cchardet/_cchardet.o
    src/cchardet/_cchardet.cpp:2351:65: error: too many arguments to function call, expected 3, have 4
        return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                     ^~~~
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include/stddef.h:100:18: note: expanded from macro 'NULL'
    #    define NULL __null
                     ^~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Users/brunopacheco/workspace/superset/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/_q/6ldlfbyd4hl0qrh0dd9kz2y00000gn/T/pip-install-ba1vcoc8/cchardet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/_q/6ldlfbyd4hl0qrh0dd9kz2y00000gn/T/pip-record-pjh8nvf6/install-record.txt --single-version-externally-managed --compile --install-headers /Users/brunopacheco/workspace/superset/venv/include/site/python3.7/cchardet" failed with error code 1 in /private/var/folders/_q/6ldlfbyd4hl0qrh0dd9kz2y00000gn/T/pip-install-ba1vcoc8/cchardet/
```

**Comment by wlhgtc** [comment]
Same Problem，Hope could be fixed！

**Comment by billtubbs** [comment]
I have this problem.  Can't install goodtables.  Is there any plan to fix for Mac OS X users?

**Comment by nikolay** [comment]
@PyYoshi Please, look into this! It's been more than an year!

**Comment by ervlh** [comment]
I have same problem. Does anyone fixed it?

**Comment by s2pstefan** [comment]
Same here. Please fix.

**Comment by xiandong79** [comment]
Same here. Please fix.

**Comment by PyPatel** [comment]
Guys, I have found a way around this. The previous version works. 
So if you want to install this you can use `pip3 install cchardet==1.0.0` to install this package.

**Comment by agnesmm** [comment]
`conda install -c conda-forge cchardet` resolved the issue for me

**Comment by kolatz** [comment]
this combination did the job:

```shell
$ pip3 list
Package    Version
---------- -------
pip        19.3.1
setuptools 42.0.2
wheel      0.33.6

$ python3 -V
Python 3.7.6

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.2

$ pip3 list # <<< result
Package         Version
--------------- -------
cchardet        2.1.5
eml-parser      1.11.6
pip             19.3.1
python-dateutil 2.8.1
setuptools      42.0.2
six             1.13.0
wheel           0.33.6
```

**Comment by vishalmhjn** [comment]
> this combination did the job:
> 
> ```shell
> $ pip3 list
> Package    Version
> ---------- -------
> pip        19.3.1
> setuptools 42.0.2
> wheel      0.33.6
> 
> $ python3 -V
> Python 3.7.6
> 
> $ sw_vers
> ProductName:	Mac OS X
> ProductVersion:	10.15.2
> 
> $ pip3 list # <<< result
> Package         Version
> --------------- -------
> cchardet        2.1.5
> eml-parser      1.11.6
> pip             19.3.1
> python-dateutil 2.8.1
> setuptools      42.0.2
> six             1.13.0
> wheel           0.33.6
> ```

Upgrading to Python 3.7.6 from 3.6 solved the issue for me.

**Comment by ThomasVrancken** [comment]
Thanks @agnesmm ! That worked for me
