### ISSUE TITLE
Clarify the intent of COPYING

### ISSUE THREAD

**Issue by frederikaalund** [PyYoshi/cChardet#54]
The COPYING text file mentions three (incompatible) licenses:
 * GPL 2
 * LGPL 2.1
 * MPL 1.1

Is cChardet multi-licensed? That is, can I freely choose between the licenses?
*or*
Do each license apply to some parts (files) of cChardet? If so, which licenses apply to which parts?

In any case, I'd like to see the intent clarified within the COPYING file itself. A good example of how to do so is [moodycamel::concurrentqueue's LICENSE](https://github.com/cameron314/concurrentqueue/blob/master/LICENSE.md).

Thanks for your work on cChardet.

**Comment by brondsem** [comment]
I am not the author(s), so cannot answer definitively, but here is what I have found:
- in `cchardet`, I've found no further licensing information in source code files, nor in git history of COPYING
- `cchardet` is a binding to `uchardet` https://github.com/PyYoshi/uchardet which has the same 3-license COPYING file
- https://github.com/PyYoshi/uchardet is a fork of https://github.com/freedesktop/uchardet
- freedesktop's uchardet:
  - has a repo at https://gitlab.freedesktop.org/uchardet/uchardet in addition to the github: https://github.com/freedesktop/uchardet
  - has the same 3-license COPYING file
  - has some History in its readme (originated with Mozilla)
  - the src/ files have this header within them which specifies the 3 licenses as alternatives:
```
/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is Mozilla Universal charset detector code.
 *
 * The Initial Developer of the Original Code is
 * Netscape Communications Corporation.
 * Portions created by the Initial Developer are Copyright (C) 2001
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *          BYVoid <byvoid.kcp@gmail.com>
 *          Jehan <jehan at girinstud.io>
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */
```
That header has some very minor variations across individual src/ files: 
- `The Original Code is` sometimes says `Mozilla Universal charset detector code` or `Mozilla Communicator client code` or `mozilla.org code`
- the copyright date changes
- the list of `Contributor(s)` sometimes is different or empty
- `The Initial Developer of the Original Code ` is individual's name instead, in at least 2 files (`nsHebrewProber.*`)

If that original licensing has been carried through to `cchardet` (and I see no reason to doubt it), then `cchardet` would be usable under any of the 3 licenses.
