### ISSUE TITLE
pyinstaller issue with cchardet 2.1.6

### ISSUE THREAD

**Issue by danielhrisca** [PyYoshi/cChardet#58]
### OS/Arch

```bash
uname_result(system='Windows', release='10', version='10.0.17763', machine='AMD64', processor='Intel64 Family 6 Model 158 Stepping 10, GenuineIntel')
```

### Python version

```bash
Python 3.6.5
```

### cChardet version

```bash
2.1.6
```

### What is the problem?
An application frozen with pyinstaller does not start raising this error. Using cChardet 2.1.5 does not cause this problem.

```
ImportError: DLL load failed: The specified module could not be found. 
```

**Comment by danielhrisca** [comment]
@PyYoshi see https://github.com/danielhrisca/asammdf/issues/346

**Comment by danielhrisca** [comment]
ping @PyYoshi

**Comment by aceohartz81** [comment]
> ### OS/Arch
> ```shell
> uname_result(system='Windows', release='10', version='10.0.17763', machine='AMD64', processor='Intel64 Family 6 Model 158 Stepping 10, GenuineIntel')
> ```
> 
> ### Python version
> ```shell
> Python 3.6.5
> ```
> 
> ### cChardet version
> ```shell
> 2.1.6
> ```
> 
> ### What is the problem?
> An application frozen with pyinstaller does not start raising this error. Using cChardet 2.1.5 does not cause this problem.
> 
> ```
> ImportError: DLL load failed: The specified module could not be found. 
> ```
> 
> #### Expected behavior
> #### Actual behavior
> #### Steps to reproduce the behavior

I am also seeing this behavior using Python 3.7.1rc2 with cchardet-2.1.7-cp37-cp37m-win_amd64.whl

**Comment by danielhrisca** [comment]
@PyYoshi @aceohartz81 
there was a similar issue in `numexpre` (see https://github.com/pydata/numexpr/issues/372)
