### ISSUE TITLE
DLL load failed while importing _cchardet

### ISSUE THREAD

**Issue by genesem** [PyYoshi/cChardet#61]
### OS/Arch
win10/x64

```bash
$ python -c 'import cchardet as chardet'
```

### Python version

python 3.8.2 x64

### cChardet version

cchardet 2.1.6

### What is the problem?
  File "C:\DevPy\DnsOverHTTPS\test.py", line 2, in <module>
    import cchardet as chardet
  File "C:\Py3\lib\site-packages\cchardet\__init__.py", line 1, in <module>
    from cchardet import _cchardet
ImportError: DLL load failed while importing _cchardet

### switched to version from
https://www.lfd.uci.edu/~gohlke/pythonlibs/#cchardet
and no errors. so bug in your imports.

**Comment by itheabyss** [comment]
i got the same problem. so it is a bug of 2.1.6?
win10 x64 20h1

anyone teach me how to fix it? thanks


```
File "C:\Users\xxx\AppData\Roaming\Python\Python38\site-packages\cchardet\__init__.py", line 1, in <module>
    from cchardet import _cchardet
ImportError: DLL load failed while importing _cchardet
```

**Comment by itheabyss** [comment]
> 
> ### switched to version from
> https://www.lfd.uci.edu/~gohlke/pythonlibs/#cchardet
> and no errors. so bug in your imports.

i've installed 'cchardet‑2.1.6‑cp38‑cp38‑win_amd64.whl', it works!
