### ISSUE TITLE
Remove bundled uchardet

### ISSUE THREAD

**Issue by fabaff** [PyYoshi/cChardet#62]
# What is the problem?

`uchardet` is bundled. This is a major concern if the package should be included in package collection of distributions as `uchardet-devel` could already be present.

#### Expected behavior

Use distro package (e.g., `uchardet-devel`) and not the bundled copy of `uchardet` during the build process. Please consider to remove the bundled `uchardet` or provide the possibility to use the installed package.

#### Actual behavior

Uses `uchardet` in `src/ext`.

#### Steps to reproduce the behavior

Install the package.

**Comment by carlwgeorge** [comment]
Not stale.

**Comment by carlwgeorge** [comment]
@PyYoshi Will you disable the stale bot on this issue?

**Comment by tooruu** [comment]
lol
