### ISSUE TITLE
Move away from nose for the unittests

### ISSUE THREAD

**Issue by fabaff** [PyYoshi/cChardet#63]
### What is the problem?
`nose` was not maintained for the last 5 years and Fedora will no longer ship it. This means that all packages which depends on `nose` are no longer able to run the unit tests during the RPM build process.

#### Expected behavior

Running the unit test with `pytest`.

#### Actual behavior

Requires `nose` to run tests.

Origin: https://bugzilla.redhat.com/show_bug.cgi?id=1834977#c1

**Comment by carlwgeorge** [comment]
.

**Comment by fabaff** [comment]
Still relevant.

**Comment by fabaff** [comment]
Would be fixed by #78
